### ISSUE TITLE
Handle Error: The account balance is less than required

### ISSUE THREAD

**Issue by gigimon** [neonevm/proxy-model.py#608] opened 2022-03-03 15:09 UTC
We need to handle this situation and write to log Info level for this without traceback
```python
Exception on process request. Type(err): <class 'RuntimeError'>, Error: The account balance is less than required: Account 822b9d6dc65830ed82a5f96292d3af832abf3174; balance = 1000000000000000; gasPrice = 651123000000; gasLimit = 48200; fee = 31384128600000000; value = 0; required_balance = 31384128600000000; , Traceback:   File "/opt/proxy/plugin/solana_rest_api.py", line 440, in process_request
    response['result'] = method(*params)
  File "/opt/proxy/plugin/solana_rest_api.py", line 363, in eth_sendRawTransaction
    raise RuntimeError("The account balance is less than required: " +
```

**Comment by afalaleev** [comment] 2022-03-03 15:28
Duplicate of #609

**Closed as completed by afalaleev** 2022-03-03 15:28 UTC
Labels: bug, duplicate
